spring:
   application:
      name: cloud-order
      
server.port: 8002

eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka

feign:
   hystrix:
      enabled: true
---
spring:
   profiles: order8007

server:
   port: 8007

---
spring:
   profiles: order8008

server:
   port: 8008