server:
   port: 80
   
spring:
   application:
      name: cloud-zuul

eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka

zuul:
   sensitiveHeaders:
   routes:
      simple:
         path: /simple/**
         url: http://www.163.com
      myForward:
         path: /us/**
         url: forward:/cloud-user
      users:
         path: /users/**
         serviceId: cloud-user
         
      cloud-order:
         path: /orders/**
      default:
         path: /**
         url: https://taobao.comm